spring.application.name=taskflow-api

# Base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:taskflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostrar sentencias SQL formateadas en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ruta de Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html